/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "myColor": {
        "en": "myColor",
        "de": "meineColor",
        "ru": "Мой цвет",
        "pt": "minhaCor",
        "nl": "mijnKleur",
        "fr": "maCouleur",
        "it": "mioColore",
        "es": "miColor",
        "pl": "mójKolor",
        "zh-cn": "我的颜色"
    },
    "myColor_tooltip": {
        "en": "Description of\nmyColor",
        "de": "Beschreibung von\nmyColor",
        "ru": "Описание\nmyColor",
        "pt": "Descrição de\nmyColor",
        "nl": "Beschrijving van\nmyColor",
        "fr": "Description de\nmyColor",
        "it": "Descrizione di\nmyColor",
        "es": "Descripción de\nmyColor",
        "pl": "Opis\nmyColor",
        "zh-cn": "\nmyColor的描述"
    },
    "htmlText": {
        "en": "htmlText",
        "de": "htmlText",
        "ru": "htmlText",
        "pt": "htmlText",
        "nl": "htmlText",
        "fr": "htmlText",
        "it": "htmlText",
        "es": "htmlText",
        "pl": "htmlText",
        "zh-cn": "htmlText"
    },
    "group_extraMyset": {
        "en": "extraMyset",
        "de": "extraMyset",
        "ru": "extraMyset",
        "pt": "extraMyset",
        "nl": "extraMyset",
        "fr": "extraMyset",
        "it": "extraMyset",
        "es": "extraMyset",
        "pl": "extraMyset",
        "zh-cn": "extraMyset"
    },
    "extraAttr": {
        "en": "extraAttr",
        "de": "extraAttr",
        "ru": "extraAttr",
        "pt": "extraAttr",
        "nl": "extraAttr",
        "fr": "extraAttr",
        "it": "extraAttr",
        "es": "extraAttr",
        "pl": "extraAttr",
        "zh-cn": "extraAttr"
    },
    "Instance": {
        "en": "Instance",
        "de": "Instanz",
        "ru": "Инстанция",
        "pt": "Instância",
        "nl": "Instantie",
        "fr": "Instance",
        "it": "Esempio",
        "es": "Instancia",
        "pl": "Instancja",
        "zh-cn": "例"
    },
    "label": {
        "en": "label",
        "de": "Beschriftung",
        "ru": "этикетка",
        "pt": "rótulo",
        "nl": "label",
        "fr": "étiquette",
        "it": "etichetta",
        "es": "etiqueta",
        "pl": "etykieta",
        "zh-cn": "标签"
    },
    "buttonStyle": {
        "en": "button style",
        "de": "Schaltflächenstil",
        "ru": "стиль кнопки",
        "pt": "estilo de botão",
        "nl": "knopstijl",
        "fr": "style de bouton",
        "it": "stile pulsante",
        "es": "estilo de botón",
        "pl": "styl przycisku",
        "zh-cn": "按钮样式"
    },
    "titleLayout": {
        "en": "title font size",
        "de": "Schriftgröße des Titels",
        "ru": "размер шрифта заголовка",
        "pt": "tamanho da fonte do título",
        "nl": "titel lettergrootte",
        "fr": "titre police taille",
        "it": "dimensione del carattere del titolo",
        "es": "tamaño de fuente del título",
        "pl": "rozmiar czcionki tytułu",
        "zh-cn": "标题字体大小"
    },
    "subtitleLayout": {
        "en": "subtitle font size",
        "de": "Schriftgröße für Untertitel",
        "ru": "размер шрифта субтитров",
        "pt": "tamanho da fonte da legenda",
        "nl": "ondertitel lettergrootte",
        "fr": "taille de la police des sous-titres",
        "it": "dimensione del carattere dei sottotitoli",
        "es": "tamaño de fuente de subtítulos",
        "pl": "rozmiar czcionki napisów",
        "zh-cn": "字幕字体大小"
    },
    "htmlLayout": {
        "en": "text style",
        "de": "Textstil",
        "ru": "стиль текста",
        "pt": "estilo de texto",
        "nl": "tekststijl",
        "fr": "style de texte",
        "it": "stile del testo",
        "es": "estilo de texto",
        "pl": "styl tekstu",
        "zh-cn": "文字样式"
    },
    "group_label": {
        "en": "labeling",
        "de": "Beschriftung",
        "ru": "маркировка",
        "pt": "marcação",
        "nl": "labeling",
        "fr": "étiquetage",
        "it": "etichettatura",
        "es": "etiquetado",
        "pl": "etykietowanie",
        "zh-cn": "标签"
    },
    "labelFalse": {
        "en": "label",
        "de": "Beschriftung",
        "ru": "этикетка",
        "pt": "rótulo",
        "nl": "label",
        "fr": "étiquette",
        "it": "etichetta",
        "es": "etiqueta",
        "pl": "etykieta",
        "zh-cn": "标签"
    },
    "labelTrue": {
        "en": "active label",
        "de": "aktive Beschriftung",
        "ru": "активная метка",
        "pt": "etiqueta ativa",
        "nl": "actief label",
        "fr": "étiquette active",
        "it": "etichetta attiva",
        "es": "etiqueta activa",
        "pl": "aktywna etykieta",
        "zh-cn": "活动标签"
    },
    "labelColorFalse": {
        "en": "label color",
        "de": "Beschriftungsfarbe",
        "ru": "цвет этикетки",
        "pt": "cor da etiqueta",
        "nl": "label kleur",
        "fr": "couleur de l'étiquette",
        "it": "colore dell'etichetta",
        "es": "color de etiqueta",
        "pl": "kolor etykiety",
        "zh-cn": "标签颜色"
    },
    "labelColorTrue": {
        "en": "active label color",
        "de": "aktive Beschriftungsfarbe",
        "ru": "активный цвет метки",
        "pt": "cor da etiqueta ativa",
        "nl": "actieve labelkleur",
        "fr": "couleur de l'étiquette active",
        "it": "colore etichetta attiva",
        "es": "color de etiqueta activa",
        "pl": "aktywny kolor etykiety",
        "zh-cn": "活动标签颜色"
    },
    "showValueLabel": {
        "en": "show value",
        "de": "Wert anzeigen",
        "ru": "показать значение",
        "pt": "mostrar valor",
        "nl": "toon waarde",
        "fr": "montrer la valeur",
        "it": "mostra valore",
        "es": "mostrar valor",
        "pl": "pokaż wartość",
        "zh-cn": "显示价值"
    },
    "valueLabelUnit": {
        "en": "unit",
        "de": "Einheit",
        "ru": "единица измерения",
        "pt": "unidade",
        "nl": "eenheid",
        "fr": "unité",
        "it": "unità",
        "es": "unidad",
        "pl": "jednostka",
        "zh-cn": "单元"
    },
    "valueMaxDecimals": {
        "en": "decimal points",
        "de": "Kommastellen",
        "ru": "десятичные точки",
        "pt": "pontos decimais",
        "nl": "decimale punten",
        "fr": "points décimaux",
        "it": "punti decimali",
        "es": "puntos decimales",
        "pl": "Punkty dziesiętne",
        "zh-cn": "小数点"
    },
    "valuePosition": {
        "en": "display position",
        "de": "Anzeigeposition",
        "ru": "положение дисплея",
        "pt": "posição de exibição",
        "nl": "weergave positie",
        "fr": "position d'affichage",
        "it": "posizione di visualizzazione",
        "es": "posición de visualización",
        "pl": "pozycja wyświetlania",
        "zh-cn": "显示位置"
    },
    "inside": {
        "en": "inside",
        "de": "innerhalb",
        "ru": "внутри",
        "pt": "dentro",
        "nl": "binnen",
        "fr": "à l'intérieur",
        "it": "dentro",
        "es": "dentro",
        "pl": "wewnątrz",
        "zh-cn": "内"
    },
    "outside": {
        "en": "outside",
        "de": "außerhalb",
        "ru": "снаружи",
        "pt": "lado de fora",
        "nl": "buiten",
        "fr": "à l'extérieur",
        "it": "al di fuori",
        "es": "fuera de",
        "pl": "na zewnątrz",
        "zh-cn": "外"
    },
    "valueLabelWidth": {
        "en": "distance label",
        "de": "Abstand Beschriftung",
        "ru": "метка расстояния",
        "pt": "etiqueta de distância",
        "nl": "afstandslabel",
        "fr": "étiquette de distance",
        "it": "etichetta della distanza",
        "es": "etiqueta de distancia",
        "pl": "etykieta odległości",
        "zh-cn": "距离标签"
    },
    "labelFalsePrepend": {
        "en": "prepend label",
        "de": "Beschriftung vorangestellt",
        "ru": "предварительно метка",
        "pt": "Anexar etiqueta",
        "nl": "label voorzetten",
        "fr": "pré-étiquette",
        "it": "anteporre etichetta",
        "es": "etiqueta de anteponer",
        "pl": "dodaj etykietę",
        "zh-cn": "前置标签"
    },
    "labelTruePrepend": {
        "en": "active prepend label",
        "de": "aktive Beschriftung vorangestellt",
        "ru": "активная метка prepend",
        "pt": "etiqueta de prefixação ativa",
        "nl": "actief prepend-label",
        "fr": "étiquette active de début",
        "it": "etichetta prepend attiva",
        "es": "etiqueta de anteponer activa",
        "pl": "aktywna etykieta poprzedzająca",
        "zh-cn": "有效的前置标签"
    },
    "labelFalseAppend": {
        "en": "append label",
        "de": "Beschriftung nachgestellt",
        "ru": "добавить ярлык",
        "pt": "acrescentar etiqueta",
        "nl": "label toevoegen",
        "fr": "apposer une étiquette",
        "it": "etichetta append",
        "es": "agregar etiqueta",
        "pl": "dołącz etykietę",
        "zh-cn": "附加标签"
    },
    "labelTrueAppend": {
        "en": "active append label",
        "de": "aktive Beschriftung nachgestellt",
        "ru": "метка активного добавления",
        "pt": "etiqueta de acréscimo ativo",
        "nl": "actief toevoeglabel",
        "fr": "étiquette active",
        "it": "etichetta append attiva",
        "es": "etiqueta de adición activa",
        "pl": "aktywna etykieta dołączania",
        "zh-cn": "活动的附加标签"
    },
    "showMarkers": {
        "en": "show Markers",
        "de": "Markierungen anzeigen",
        "ru": "показать маркеры",
        "pt": "mostrar marcadores",
        "nl": "markeringen weergeven",
        "fr": "montrer les marqueurs",
        "it": "mostra marcatori",
        "es": "mostrar marcadores",
        "pl": "pokaż Markery",
        "zh-cn": "显示标记"
    },
    "valueLabelMin": {
        "en": "label for value less than min",
        "de": "Beschriftung für Wert kleiner als min",
        "ru": "метка для значения меньше мин",
        "pt": "rótulo para valor menor que min",
        "nl": "label voor waarde minder dan min",
        "fr": "étiquette pour valeur inférieure à min",
        "it": "etichetta per valore inferiore a min",
        "es": "etiqueta para valor menor que min",
        "pl": "etykieta dla wartości mniejszej niż min",
        "zh-cn": "标签值小于min"
    },
    "valueLabelMax": {
        "en": "label for value greater than max",
        "de": "Beschriftung für Wert größer als max",
        "ru": "метка для значения больше, чем max",
        "pt": "rótulo para valor maior que max",
        "nl": "label voor waarde groter dan max",
        "fr": "étiquette pour valeur supérieure à max",
        "it": "etichetta per valore maggiore di max",
        "es": "etiqueta para valor mayor que max",
        "pl": "etykieta dla wartości większej niż maks",
        "zh-cn": "标签值大于最大值"
    },
    "labelClickActive": {
        "en": "activate label click",
        "de": "Beschriftungs-Klick aktivieren",
        "ru": "активировать ярлык нажмите",
        "pt": "ativar clique de etiqueta",
        "nl": "activeer label klik",
        "fr": "activer l'étiquette cliquer",
        "it": "attiva il clic sull'etichetta",
        "es": "activar clic de etiqueta",
        "pl": "aktywuj kliknięcie etykiety",
        "zh-cn": "激活标签点击"
    },
    "group_icon": {
        "en": "icon",
        "de": "Symbol",
        "ru": "икона",
        "pt": "ícone",
        "nl": "icoon",
        "fr": "icône",
        "it": "icona",
        "es": "icono",
        "pl": "Ikona",
        "zh-cn": "图标"
    },
    "imageFalse": {
        "en": "icon",
        "de": "Symbol",
        "ru": "икона",
        "pt": "ícone",
        "nl": "icoon",
        "fr": "icône",
        "it": "icona",
        "es": "icono",
        "pl": "Ikona",
        "zh-cn": "图标"
    },
    "imageTrue": {
        "en": "active image",
        "de": "aktives Bild",
        "ru": "активное изображение",
        "pt": "imagem ativa",
        "nl": "actieve afbeelding",
        "fr": "image active",
        "it": "immagine attiva",
        "es": "imagen activa",
        "pl": "aktywny obraz",
        "zh-cn": "活动图像"
    },
    "invertImageTrue": {
        "en": "invert active image",
        "de": "Aktives Bild invertieren",
        "ru": "инвертировать активное изображение",
        "pt": "inverter imagem ativa",
        "nl": "actieve afbeelding omkeren",
        "fr": "inverser l'image active",
        "it": "inverti immagine attiva",
        "es": "invertir imagen activa",
        "pl": "odwróć aktywny obraz",
        "zh-cn": "反转活动图像"
    },
    "iconHeight": {
        "en": "image height",
        "de": "Bildhöhe",
        "ru": "высота изображения",
        "pt": "Altura da imagem",
        "nl": "afbeeldingshoogte",
        "fr": "hauteur de l'image",
        "it": "altezza dell'immagine",
        "es": "Altura de imagen",
        "pl": "Wysokość obrazu",
        "zh-cn": "影像高度"
    },
    "group_color": {
        "en": "colors",
        "de": "Farben",
        "ru": "цвета",
        "pt": "cores",
        "nl": "kleuren",
        "fr": "couleurs",
        "it": "colori",
        "es": "colores",
        "pl": "zabarwienie",
        "zh-cn": "颜色"
    },
    "colorBgFalse": {
        "en": "background",
        "de": "Hintergrund",
        "ru": "фон",
        "pt": "fundo",
        "nl": "achtergrond",
        "fr": "Contexte",
        "it": "sfondo",
        "es": "antecedentes",
        "pl": "tło",
        "zh-cn": "背景"
    },
    "colorBgTrue": {
        "en": "active background",
        "de": "aktiver Hintergrund",
        "ru": "активный фон",
        "pt": "fundo ativo",
        "nl": "actieve achtergrond",
        "fr": "fond actif",
        "it": "sfondo attivo",
        "es": "fondo activo",
        "pl": "aktywne tło",
        "zh-cn": "活动背景"
    },
    "labelColorBgFalse": {
        "en": "label background",
        "de": "Hintergrund Beschriftung",
        "ru": "фон метки",
        "pt": "fundo da etiqueta",
        "nl": "label achtergrond",
        "fr": "étiquette fond",
        "it": "etichetta di sfondo",
        "es": "etiqueta de fondo",
        "pl": "tło etykiety",
        "zh-cn": "标签背景"
    },
    "labelColorBgTrue": {
        "en": "active label background",
        "de": "aktiver Hintergrund Beschriftung",
        "ru": "фон активной метки",
        "pt": "fundo do rótulo ativo",
        "nl": "actieve label achtergrond",
        "fr": "étiquette active",
        "it": "etichetta attiva sullo sfondo",
        "es": "fondo de etiqueta activa",
        "pl": "aktywne tło etykiety",
        "zh-cn": "活动标签背景"
    },
    "colorPress": {
        "en": "color pressed",
        "de": "Farbe gedrückt",
        "ru": "цвет нажал",
        "pt": "cor pressionada",
        "nl": "kleur ingedrukt",
        "fr": "couleur pressée",
        "it": "colore premuto",
        "es": "color presionado",
        "pl": "kolor wciśnięty",
        "zh-cn": "压色"
    },
    "colorProgress": {
        "en": "color progress",
        "de": "Farbe Fortschritt",
        "ru": "прогресс цвета",
        "pt": "progresso da cor",
        "nl": "kleur vooruitgang",
        "fr": "progression de la couleur",
        "it": "progresso del colore",
        "es": "progreso de color",
        "pl": "postęp kolorów",
        "zh-cn": "颜色进度"
    },
    "colorOneCondition": {
        "en": "condition for color 1 progress [>]",
        "de": "Bedingung für Farbe 1 Fortschritt [>]",
        "ru": "условие для прогресса цвета 1 [>]",
        "pt": "condição para o progresso da cor 1 [>]",
        "nl": "voorwaarde voor voortgang kleur 1 [>]",
        "fr": "condition pour la progression de la couleur 1 [>]",
        "it": "condizione per avanzamento colore 1 [>]",
        "es": "condición para el progreso del color 1 [>]",
        "pl": "warunek postępu koloru 1 [>]",
        "zh-cn": "颜色1进度的条件[>]"
    },
    "colorOne": {
        "en": "color 1 progress",
        "de": "Farbe 1 Fortschritt",
        "ru": "цвет 1 прогресс",
        "pt": "cor 1 progresso",
        "nl": "kleur 1 voortgang",
        "fr": "couleur 1 progrès",
        "it": "avanzamento colore 1",
        "es": "color 1 progreso",
        "pl": "postęp koloru 1",
        "zh-cn": "颜色1进度"
    },
    "colorTwoCondition": {
        "en": "condition for color 2 progress [>]",
        "de": "Bedingung für Farbe 2 Fortschritt [>]",
        "ru": "условие для прогресса цвета 2 [>]",
        "pt": "condição para o progresso da cor 2 [>]",
        "nl": "voorwaarde voor voortgang kleur 2 [>]",
        "fr": "condition pour la progression de la couleur 2 [>]",
        "it": "condizione per avanzamento colore 2 [>]",
        "es": "condición para el progreso del color 2 [>]",
        "pl": "warunek postępu koloru 2 [>]",
        "zh-cn": "颜色2进度的条件[>]"
    },
    "colorTwo": {
        "en": "color 2 progress",
        "de": "Farbe 2 Fortschritt",
        "ru": "цвет 2 прогресс",
        "pt": "progresso da cor 2",
        "nl": "kleur 2 voortgang",
        "fr": "couleur 2 progrès",
        "it": "avanzamento colore 2",
        "es": "progreso del color 2",
        "pl": "kolor 2 postępu",
        "zh-cn": "颜色2进展"
    },
    "colorSwitchTrue": {
        "en": "active switch color",
        "de": "aktive Schalterfarbe",
        "ru": "активный переключатель цвета",
        "pt": "cor do interruptor ativo",
        "nl": "actieve schakelaar kleur",
        "fr": "couleur active du commutateur",
        "it": "colore interruttore attivo",
        "es": "color de interruptor activo",
        "pl": "aktywny kolor przełącznika",
        "zh-cn": "活动开关颜色"
    },
    "colorSlider": {
        "en": "color Slider",
        "de": "Farbe Regler",
        "ru": "цветной слайдер",
        "pt": "controle deslizante de cor",
        "nl": "kleuren schuifregelaar",
        "fr": "couleur Slider",
        "it": "cursore a colori",
        "es": "control deslizante de color",
        "pl": "suwak koloru",
        "zh-cn": "彩色滑块"
    },
    "colorSliderBg": {
        "en": "background",
        "de": "Hintergrund",
        "ru": "фон",
        "pt": "fundo",
        "nl": "achtergrond",
        "fr": "Contexte",
        "it": "sfondo",
        "es": "antecedentes",
        "pl": "tło",
        "zh-cn": "背景"
    },
    "colorCheckBox": {
        "en": "active checkbox color",
        "de": "Farbe des aktiven Kontrollkästchens",
        "ru": "активный флажок цвет",
        "pt": "cor da caixa de seleção ativa",
        "nl": "actieve selectievakje kleur",
        "fr": "couleur de la case à cocher active",
        "it": "colore della casella di controllo attivo",
        "es": "color de casilla activa",
        "pl": "aktywny kolor pola wyboru",
        "zh-cn": "活动复选框颜色"
    },
    "group_drawerLabels": {
        "en": "label for navigation bar",
        "de": "Navigationsleiste: Beschriftungen",
        "ru": "ярлык для панели навигации",
        "pt": "etiqueta para barra de navegação",
        "nl": "label voor navigatiebalk",
        "fr": "étiquette pour la barre de navigation",
        "it": "etichetta per barra di navigazione",
        "es": "etiqueta para barra de navegación",
        "pl": "etykieta dla paska nawigacji",
        "zh-cn": "导航栏标签"
    },
    "labels": {
        "en": "label",
        "de": "Beschriftung",
        "ru": "этикетка",
        "pt": "rótulo",
        "nl": "label",
        "fr": "étiquette",
        "it": "etichetta",
        "es": "etiqueta",
        "pl": "etykieta",
        "zh-cn": "标签"
    },
    "group_drawerHeaders": {
        "en": "headers for navigation bar",
        "de": "Navigationsleiste: Überschriften",
        "ru": "заголовки для панели навигации",
        "pt": "cabeçalhos da barra de navegação",
        "nl": "headers voor navigatiebalk",
        "fr": "en-têtes pour la barre de navigation",
        "it": "intestazioni per la barra di navigazione",
        "es": "encabezados para barra de navegación",
        "pl": "nagłówki paska nawigacji",
        "zh-cn": "导航栏标题"
    },
    "headers": {
        "en": "header",
        "de": "Überschrift",
        "ru": "заголовок",
        "pt": "cabeçalho",
        "nl": "hoofd",
        "fr": "entête",
        "it": "intestazione",
        "es": "encabezamiento",
        "pl": "nagłówek",
        "zh-cn": "头"
    },
    "group_drawerDivider": {
        "en": "dividers for navigation bar",
        "de": "Navigationsleiste: Trennlinien",
        "ru": "разделители для панели навигации",
        "pt": "divisores para barra de navegação",
        "nl": "scheidingslijnen voor navigatiebalk",
        "fr": "séparateurs pour barre de navigation",
        "it": "divisori per barra di navigazione",
        "es": "divisores para barra de navegación",
        "pl": "przekładki do paska nawigacji",
        "zh-cn": "导航栏分隔线"
    },
    "dividers": {
        "en": "divider",
        "de": "Trennlinie",
        "ru": "делитель",
        "pt": "divisor",
        "nl": "verdeler",
        "fr": "diviseur",
        "it": "divisore",
        "es": "divisor",
        "pl": "rozdzielacz",
        "zh-cn": "分频器"
    },
    "group_drawerIcons": {
        "en": "icons for navigation bar",
        "de": "Navigationsleiste: Bilder",
        "ru": "иконки для панели навигации",
        "pt": "ícones para barra de navegação",
        "nl": "pictogrammen voor navigatiebalk",
        "fr": "icônes pour la barre de navigation",
        "it": "icone per la barra di navigazione",
        "es": "iconos para barra de navegación",
        "pl": "ikony paska nawigacji",
        "zh-cn": "导航栏图标"
    },
    "iconDrawer": {
        "en": "icon",
        "de": "Bild",
        "ru": "икона",
        "pt": "ícone",
        "nl": "icoon",
        "fr": "icône",
        "it": "icona",
        "es": "icono",
        "pl": "Ikona",
        "zh-cn": "图标"
    },
    "group_drawerLayout": {
        "en": "navigation bar layout",
        "de": "Navigationsleiste: Layout",
        "ru": "расположение панели навигации",
        "pt": "layout da barra de navegação",
        "nl": "navigatiebalk lay-out",
        "fr": "disposition de la barre de navigation",
        "it": "layout della barra di navigazione",
        "es": "diseño de la barra de navegación",
        "pl": "układ paska nawigacyjnego",
        "zh-cn": "导航栏布局"
    },
    "drawerLayout": {
        "en": "layout",
        "de": "Layout",
        "ru": "расположение",
        "pt": "disposição",
        "nl": "lay-out",
        "fr": "disposition",
        "it": "disposizione",
        "es": "diseño",
        "pl": "układ",
        "zh-cn": "布局"
    },
    "drawerWidth": {
        "en": "width",
        "de": "Breite",
        "ru": "ширина",
        "pt": "largura",
        "nl": "breedte",
        "fr": "largeur",
        "it": "larghezza",
        "es": "anchura",
        "pl": "szerokość",
        "zh-cn": "宽度"
    },
    "showHeader": {
        "en": "show header",
        "de": "Kopfzeile anzeigen",
        "ru": "показать заголовок",
        "pt": "Mostrar Cabeçalho",
        "nl": "toon koptekst",
        "fr": "Afficher en-tête",
        "it": "mostra intestazione",
        "es": "Mostrar Encabezado",
        "pl": "pokaż nagłówek",
        "zh-cn": "显示标题"
    },
    "headerLabel": {
        "en": "header text",
        "de": "Kopfzeile Text",
        "ru": "текст заголовка",
        "pt": "texto do cabeçalho",
        "nl": "koptekst",
        "fr": "en-tête",
        "it": "titolo",
        "es": "texto de cabecera",
        "pl": "tekst nagłówka",
        "zh-cn": "标题文本"
    },
    "showLabels": {
        "en": "show list items labels",
        "de": "Beschriftungen für Listenelemente anzeigen",
        "ru": "показать метки элементов списка",
        "pt": "mostrar etiquetas de itens da lista",
        "nl": "labels voor lijstitems weergeven",
        "fr": "afficher les étiquettes des éléments de liste",
        "it": "mostra le etichette degli elementi dell'elenco",
        "es": "mostrar etiquetas de elementos de la lista",
        "pl": "pokaż etykiety elementów listy",
        "zh-cn": "显示清单项目标签"
    },
    "drawerIconHeight": {
        "en": "list items icon height",
        "de": "Höhe des Symbols für Listenelemente",
        "ru": "высота значка списка элементов",
        "pt": "altura do ícone dos itens da lista",
        "nl": "lijstitems pictogram hoogte",
        "fr": "liste des éléments icône hauteur",
        "it": "elenco elementi icona altezza",
        "es": "altura de icono de elementos de lista",
        "pl": "wysokość ikony elementów listy",
        "zh-cn": "列出项目图标的高度"
    },
    "listItemTextSize": {
        "en": "list items font size",
        "de": "Listenelemente Schriftgröße",
        "ru": "размер шрифта списка элементов",
        "pt": "tamanho da fonte dos itens da lista",
        "nl": "lijst met lettertypegrootte",
        "fr": "liste des éléments taille de la police",
        "it": "elenca le dimensioni del carattere degli elementi",
        "es": "lista de elementos tamaño de fuente",
        "pl": "rozmiar czcionki listy elementów",
        "zh-cn": "列出项目的字体大小"
    },
    "group_drawerColors": {
        "en": "navigation bar colors",
        "de": "Navigationsleiste: Farben",
        "ru": "цвета панели навигации",
        "pt": "cores da barra de navegação",
        "nl": "kleuren van de navigatiebalk",
        "fr": "couleurs de la barre de navigation",
        "it": "colori della barra di navigazione",
        "es": "colores de la barra de navegación",
        "pl": "kolory paska nawigacyjnego",
        "zh-cn": "导航栏颜色"
    },
    "colorDrawerBackground": {
        "en": "background",
        "de": "Hintergrund",
        "ru": "фон",
        "pt": "fundo",
        "nl": "achtergrond",
        "fr": "Contexte",
        "it": "sfondo",
        "es": "antecedentes",
        "pl": "tło",
        "zh-cn": "背景"
    },
    "colorDrawerHeaderBackground": {
        "en": "header background color",
        "de": "Kopfzeile Hintergrund",
        "ru": "цвет фона заголовка",
        "pt": "cor de fundo do cabeçalho",
        "nl": "koptekst achtergrondkleur",
        "fr": "couleur de fond de l'en-tête",
        "it": "colore di sfondo dell'intestazione",
        "es": "color de fondo del encabezado",
        "pl": "kolor tła nagłówka",
        "zh-cn": "标头背景色"
    },
    "colorListItemSelected": {
        "en": "active element",
        "de": "aktives Element",
        "ru": "активный элемент",
        "pt": "elemento ativo",
        "nl": "actief element",
        "fr": "élément actif",
        "it": "elemento attivo",
        "es": "elemento activo",
        "pl": "aktywny element",
        "zh-cn": "活性元素"
    },
    "colorListItemHover": {
        "en": "select element",
        "de": "Element selektiert / hover",
        "ru": "выбрать элемент",
        "pt": "selecionar elemento",
        "nl": "selecteer element",
        "fr": "sélectionner un élément",
        "it": "seleziona elemento",
        "es": "seleccione elemento",
        "pl": "wybierz element",
        "zh-cn": "选择元素"
    },
    "colorListItemText": {
        "en": "label",
        "de": "Beschriftung",
        "ru": "этикетка",
        "pt": "rótulo",
        "nl": "label",
        "fr": "étiquette",
        "it": "etichetta",
        "es": "etiqueta",
        "pl": "etykieta",
        "zh-cn": "标签"
    },
    "colorListItemHeaders": {
        "en": "headers color",
        "de": "Überschriften",
        "ru": "цвет заголовков",
        "pt": "cor dos cabeçalhos",
        "nl": "headers kleur",
        "fr": "couleur des en-têtes",
        "it": "colore delle intestazioni",
        "es": "color de encabezados",
        "pl": "kolor nagłówków",
        "zh-cn": "标头颜色"
    },
    "colorListItemTextSelected": {
        "en": "active label",
        "de": "aktive Beschriftungen",
        "ru": "активная метка",
        "pt": "etiqueta ativa",
        "nl": "actief label",
        "fr": "étiquette active",
        "it": "etichetta attiva",
        "es": "etiqueta activa",
        "pl": "aktywna etykieta",
        "zh-cn": "活动标签"
    },
    "colorListItemDivider": {
        "en": "divider color",
        "de": "Trennlinie",
        "ru": "цвет делителя",
        "pt": "cor do divisor",
        "nl": "scheidingskleur",
        "fr": "couleur du séparateur",
        "it": "colore del divisore",
        "es": "color divisor",
        "pl": "kolor dzielnika",
        "zh-cn": "分隔线颜色"
    },
    "group_topAppBarLayout": {
        "en": "top app bar layout",
        "de": "Top App Bar Layout",
        "ru": "макет верхней панели приложения",
        "pt": "layout da barra de aplicativos superior",
        "nl": "bovenste app-balkindeling",
        "fr": "top mise en page de la barre d'application",
        "it": "layout della barra delle app principali",
        "es": "diseño de la barra de la aplicación superior",
        "pl": "górny układ paska aplikacji",
        "zh-cn": "顶部应用栏布局"
    },
    "titleTopAppBar": {
        "en": "title",
        "de": "Titel",
        "ru": "заглавие",
        "pt": "título",
        "nl": "titel",
        "fr": "Titre",
        "it": "titolo",
        "es": "título",
        "pl": "tytuł",
        "zh-cn": "标题"
    },
    "colorTopAppBarTitle": {
        "en": "title color",
        "de": "Titelfarbe",
        "ru": "цвет заголовка",
        "pt": "cor do título",
        "nl": "titel kleur",
        "fr": "couleur du titre",
        "it": "colore del titolo",
        "es": "color del título",
        "pl": "kolor tytułu",
        "zh-cn": "标题颜色"
    },
    "colorTopAppBarBackground": {
        "en": "background color",
        "de": "Hintergrundfarbe",
        "ru": "фоновый цвет",
        "pt": "cor de fundo",
        "nl": "Achtergrond kleur",
        "fr": "Couleur de l'arrière plan",
        "it": "colore di sfondo",
        "es": "color de fondo",
        "pl": "kolor tła",
        "zh-cn": "背景颜色"
    },
    "showSelectedItemAsTitle": {
        "en": "show title of selected navigation bar item",
        "de": "Titel des ausgewählten Navigationsleistenelements anzeigen",
        "ru": "показать заголовок выбранного элемента панели навигации",
        "pt": "mostra o título do item da barra de navegação selecionada",
        "nl": "toon de titel van het geselecteerde navigatiebalkitem",
        "fr": "affiche le titre de l'élément de barre de navigation sélectionné",
        "it": "mostra il titolo della barra di navigazione selezionata",
        "es": "muestra el título del elemento de barra de navegación seleccionado",
        "pl": "pokaż tytuł wybranego elementu paska nawigacji",
        "zh-cn": "显示所选导航栏项目的标题"
    },
    "invertImage": {
        "en": "invert image color",
        "de": "Bildfarbe umkehren",
        "ru": "инвертировать цвет изображения",
        "pt": "inverter cor da imagem",
        "nl": "beeldkleur omkeren",
        "fr": "inverser la couleur de l'image",
        "it": "inverti il colore dell'immagine",
        "es": "invertir el color de la imagen",
        "pl": "odwróć kolor obrazu",
        "zh-cn": "反转图像颜色"
    },
    "knobSize": {
        "en": "knob size",
        "de": "Knopfgröße",
        "ru": "размер ручки",
        "pt": "tamanho do botão",
        "nl": "knop maat",
        "fr": "taille du bouton",
        "it": "dimensione della manopola",
        "es": "tamaño de la perilla",
        "pl": "rozmiar pokrętła",
        "zh-cn": "旋钮大小"
    },
    "knobSmall": {
        "en": "small",
        "de": "normal",
        "ru": "небольшой",
        "pt": "pequeno",
        "nl": "klein",
        "fr": "petit",
        "it": "piccolo",
        "es": "pequeña",
        "pl": "mały",
        "zh-cn": "小"
    },
    "knobMedium": {
        "en": "medium",
        "de": "Wurschtfinger",
        "ru": "Средняя",
        "pt": "médio",
        "nl": "medium",
        "fr": "moyen",
        "it": "medio",
        "es": "medio",
        "pl": "średni",
        "zh-cn": "介质"
    },
    "knobBig": {
        "en": "big",
        "de": "große Wurschtfinger",
        "ru": "большой",
        "pt": "grande",
        "nl": "groot",
        "fr": "gros",
        "it": "grande",
        "es": "grande",
        "pl": "duży",
        "zh-cn": "大"
    },
    "group_chartLayout": {
        "en": "chart layout:",
        "de": "Diagramm Layout:",
        "ru": "макет диаграммы:",
        "pt": "layout do gráfico:",
        "nl": "grafiek layout:",
        "fr": "mise en page graphique:",
        "it": "layout grafico:",
        "es": "diseño del gráfico:",
        "pl": "układ wykresu:",
        "zh-cn": "图表布局："
    },
    "group_barLayout": {
        "en": "bar chart layout:",
        "de": "Balkendiagramm Layout:",
        "ru": "макет гистограммы:",
        "pt": "layout do gráfico de barras:",
        "nl": "lay-out van staafdiagram:",
        "fr": "Diagramme à barres:",
        "it": "layout grafico a barre:",
        "es": "diseño del gráfico de barras:",
        "pl": "układ wykresu słupkowego:",
        "zh-cn": "条形图布局："
    },
    "group_pieLayout": {
        "en": "pie chart layout:",
        "de": "Kreisdiagramm Layout:",
        "ru": "макет круговой диаграммы:",
        "pt": "layout do gráfico de pizza:",
        "nl": "cirkeldiagramindeling:",
        "fr": "graphique en camembert:",
        "it": "layout grafico a torta:",
        "es": "diseño de gráfico circular:",
        "pl": "układ wykresu kołowego:",
        "zh-cn": "饼图布局："
    },
    "group_barValuesLayout": {
        "en": "bar chart values layout:",
        "de": "Balkendiagrammwerte Layout:",
        "ru": "макет значений гистограммы:",
        "pt": "layout dos valores do gráfico de barras:",
        "nl": "lay-out waarden staafdiagram:",
        "fr": "Diagramme à barres mise en page:",
        "it": "layout valori grafico a barre:",
        "es": "diseño de valores del gráfico de barras:",
        "pl": "układ wartości wykresu słupkowego:",
        "zh-cn": "条形图值布局："
    },
    "group_pieValuesLayout": {
        "en": "pie chart values layout:",
        "de": "Kreisdiagrammwerte Layout:",
        "ru": "макет значений круговой диаграммы:",
        "pt": "layout dos valores do gráfico de setores circulares:",
        "nl": "lay-out waarden cirkeldiagram:",
        "fr": "Mise en page des valeurs du graphique à secteurs:",
        "it": "layout valori grafico a torta:",
        "es": "diseño de valores de gráfico circular:",
        "pl": "układ wartości wykresu kołowego:",
        "zh-cn": "饼图值布局："
    },
    "group_legendLayout": {
        "en": "legend layout:",
        "de": "Legenden Layout:",
        "ru": "макет легенды:",
        "pt": "layout da legenda:",
        "nl": "legenda lay-out:",
        "fr": "disposition de la légende:",
        "it": "layout legenda:",
        "es": "diseño de leyenda:",
        "pl": "układ legendy:",
        "zh-cn": "图例布局："
    },
    "group_tooltipLayout": {
        "en": "tooltip layout:",
        "de": "Tooltip Layout:",
        "ru": "макет всплывающей подсказки:",
        "pt": "layout da dica de ferramenta:",
        "nl": "knopinfo lay-out:",
        "fr": "mise en page info-bulle:",
        "it": "layout della descrizione comandi:",
        "es": "diseño de información sobre herramientas:",
        "pl": "układ podpowiedzi:",
        "zh-cn": "工具提示布局："
    },
    "group_barColors": {
        "en": "bar chart colors:",
        "de": "Balkendiagrammfarben:",
        "ru": "цвета гистограммы:",
        "pt": "cores do gráfico de barras:",
        "nl": "staafdiagram kleuren:",
        "fr": "couleurs du graphique à barres:",
        "it": "colori del grafico a barre:",
        "es": "colores del gráfico de barras:",
        "pl": "kolory wykresu słupkowego:",
        "zh-cn": "条形图颜色："
    },
    "group_pieColors": {
        "en": "pie chart colors:",
        "de": "Kreisdiagrammfarben:",
        "ru": "Цвета круговой диаграммы:",
        "pt": "cores do gráfico de pizza:",
        "nl": "cirkeldiagram kleuren:",
        "fr": "camembert couleurs:",
        "it": "colori del grafico a torta:",
        "es": "colores del gráfico circular:",
        "pl": "kolory wykresu kołowego:",
        "zh-cn": "饼图颜色："
    },
    "group_valueTextColors": {
        "en": "value text colors",
        "de": "Wert Textfarben",
        "ru": "значение цвета текста",
        "pt": "valor cores de texto",
        "nl": "waarde tekstkleuren",
        "fr": "Valoriser les couleurs du texte",
        "it": "valorizza i colori del testo",
        "es": "colores de texto de valor",
        "pl": "cenić kolory tekstu",
        "zh-cn": "值文字颜色"
    },
    "group_labelValuesAppend": {
        "en": "value text appendix",
        "de": "Wert Textanhang",
        "ru": "текстовое приложение значения",
        "pt": "apêndice de texto com valor",
        "nl": "waarde tekst bijlage",
        "fr": "annexe texte valeur",
        "it": "appendice testo valore",
        "es": "apéndice de texto de valor",
        "pl": "tekst wartości dodatku",
        "zh-cn": "值文本附录"
    },
    "chartType": {
        "en": "chart type",
        "de": "Diagramm Typ",
        "ru": "тип диаграммы",
        "pt": "tipo de gráfico",
        "nl": "grafiektype",
        "fr": "type de graphique",
        "it": "tipo di grafico",
        "es": "tipo de gráfico",
        "pl": "typ wykresu",
        "zh-cn": "图表类型"
    },
    "animationDuration": {
        "en": "animation duration",
        "de": "Animationsdauer",
        "ru": "продолжительность анимации",
        "pt": "duração da animação",
        "nl": "animatieduur",
        "fr": "durée de l'animation",
        "it": "durata dell'animazione",
        "es": "duración de la animación",
        "pl": "czas trwania animacji",
        "zh-cn": "动画时长"
    },
    "globalColor": {
        "en": "global color",
        "de": "globale Farbe",
        "ru": "глобальный цвет",
        "pt": "cor global",
        "nl": "globale kleur",
        "fr": "couleur globale",
        "it": "colore globale",
        "es": "color global",
        "pl": "globalny kolor",
        "zh-cn": "全球色彩"
    },
    "barLabelText": {
        "en": "bar legend text",
        "de": "Balkenlegendentext",
        "ru": "текст легенды бара",
        "pt": "texto da legenda da barra",
        "nl": "tekst van balklegenda",
        "fr": "texte de la légende",
        "it": "testo legenda barra",
        "es": "texto de la leyenda de la barra",
        "pl": "tekst legendy słupkowej",
        "zh-cn": "酒吧图例文字"
    },
    "hoverColor": {
        "en": "hover color",
        "de": "Farbe selektiert / hover",
        "ru": "цвет зависания",
        "pt": "pairar cor",
        "nl": "zweef kleur",
        "fr": "vol stationnaire couleur",
        "it": "colore al passaggio del mouse",
        "es": "color de libración",
        "pl": "kolor najechania",
        "zh-cn": "悬停颜色"
    },
    "borderColor": {
        "en": "border color",
        "de": "Rahmenfarbe",
        "ru": "цвет границы",
        "pt": "Cor da borda",
        "nl": "rand kleur",
        "fr": "couleur de la bordure",
        "it": "colore del bordo",
        "es": "color del borde",
        "pl": "kolor ramki",
        "zh-cn": "边框颜色"
    },
    "hoverBorderColor": {
        "en": "hover border color",
        "de": "Rahmenfarbe selektiert / hover",
        "ru": "цвет рамки при наведении",
        "pt": "passar a cor da borda",
        "nl": "beweeg de randkleur",
        "fr": "couleur de bordure en vol stationnaire",
        "it": "colore del bordo al passaggio del mouse",
        "es": "color del borde flotante",
        "pl": "najedź na kolor obramowania",
        "zh-cn": "悬停边框颜色"
    },
    "borderWidth": {
        "en": "border width",
        "de": "Rahmenbreite",
        "ru": "ширина рамки",
        "pt": "largura da borda",
        "nl": "grensbreedte",
        "fr": "largeur de la bordure",
        "it": "larghezza del bordo",
        "es": "ancho del borde",
        "pl": "szerokość granicy",
        "zh-cn": "边框宽度"
    },
    "hoverBorderWidth": {
        "en": "selected border width",
        "de": "Rahmenbreite selektiert / hover",
        "ru": "выбранная ширина границы",
        "pt": "largura da borda selecionada",
        "nl": "geselecteerde randbreedte",
        "fr": "largeur de bordure sélectionnée",
        "it": "larghezza del bordo selezionata",
        "es": "ancho de borde seleccionado",
        "pl": "wybrana szerokość ramki",
        "zh-cn": "选定的边框宽度"
    },
    "showValues": {
        "en": "show values",
        "de": "Werte anzeigen",
        "ru": "показать значения",
        "pt": "mostrar valores",
        "nl": "toon waarden",
        "fr": "montrer les valeurs",
        "it": "mostra valori",
        "es": "mostrar valores",
        "pl": "pokaż wartości",
        "zh-cn": "显示价值"
    },
    "valuesMaxDecimals": {
        "en": "maximal decimales",
        "de": "maximale Dezimalstellen",
        "ru": "максимальные десятичные дроби",
        "pt": "dizimadas máximas",
        "nl": "maximale decimalen",
        "fr": "décimales maximales",
        "it": "decimali massimi",
        "es": "decimales máximos",
        "pl": "maksymalne dziesiętne",
        "zh-cn": "最大小数"
    },
    "valuesAppendText": {
        "en": "values text appendix",
        "de": "Werte Textanhang",
        "ru": "текстовое приложение значений",
        "pt": "valores texto apêndice",
        "nl": "waarden tekst bijlage",
        "fr": "annexe texte des valeurs",
        "it": "valori appendice testo",
        "es": "apéndice de texto de valores",
        "pl": "wartości tekstowy załącznik",
        "zh-cn": "值文本附录"
    },
    "valuesFontColor": {
        "en": "font color",
        "de": "Schriftfarbe",
        "ru": "Цвет шрифта",
        "pt": "cor da fonte",
        "nl": "letterkleur",
        "fr": "couleur de la police",
        "it": "colore del carattere",
        "es": "color de fuente",
        "pl": "kolor czcionki",
        "zh-cn": "字体颜色"
    },
    "valuesFontFamily": {
        "en": "font",
        "de": "Schriftart",
        "ru": "шрифт",
        "pt": "Fonte",
        "nl": "doopvont",
        "fr": "Police de caractère",
        "it": "font",
        "es": "fuente",
        "pl": "czcionka",
        "zh-cn": "字形"
    },
    "valuesFontSize": {
        "en": "font size",
        "de": "Schriftgröße",
        "ru": "размер шрифта",
        "pt": "tamanho da fonte",
        "nl": "lettertypegrootte",
        "fr": "taille de police",
        "it": "dimensione del font",
        "es": "tamaño de fuente",
        "pl": "rozmiar czcionki",
        "zh-cn": "字体大小"
    },
    "valuesPositionAnchor": {
        "en": "positioning",
        "de": "Positionierung",
        "ru": "позиционирование",
        "pt": "posicionamento",
        "nl": "positionering",
        "fr": "positionnement",
        "it": "posizionamento",
        "es": "posicionamiento",
        "pl": "pozycjonowanie",
        "zh-cn": "定位"
    },
    "valuesPositionAlign": {
        "en": "position align",
        "de": "Position ausrichten",
        "ru": "выравнивание положения",
        "pt": "alinhar posição",
        "nl": "positie uitlijnen",
        "fr": "aligner la position",
        "it": "allineare la posizione",
        "es": "posición alinear",
        "pl": "wyrównać pozycję",
        "zh-cn": "位置对齐"
    },
    "valuesTextAlign": {
        "en": "text align",
        "de": "Textausrichtung",
        "ru": "выравнивание текста",
        "pt": "alinhamento de texto",
        "nl": "tekst uitlijnen",
        "fr": "aligner le texte",
        "it": "allineamento del testo",
        "es": "Alineación texto",
        "pl": "wyrównaj tekst",
        "zh-cn": "文字对齐"
    },
    "valuesRotation": {
        "en": "text rotation",
        "de": "Textrotation",
        "ru": "поворот текста",
        "pt": "rotação de texto",
        "nl": "tekst rotatie",
        "fr": "rotation du texte",
        "it": "rotazione del testo",
        "es": "rotación de texto",
        "pl": "obrót tekstu",
        "zh-cn": "文字旋转"
    },
    "showLegend": {
        "en": "show legend",
        "de": "Legende anzeigen",
        "ru": "показать легенду",
        "pt": "mostrar legenda",
        "nl": "toon legende",
        "fr": "montrer la légende",
        "it": "mostra legenda",
        "es": "Mostrar leyenda",
        "pl": "pokaż legendę",
        "zh-cn": "显示传奇"
    },
    "legendPosition": {
        "en": "legend position",
        "de": "Legendenposition",
        "ru": "положение легенды",
        "pt": "posição da legenda",
        "nl": "legende positie",
        "fr": "position de la légende",
        "it": "posizione della legenda",
        "es": "posición de leyenda",
        "pl": "pozycja legendy",
        "zh-cn": "图例位置"
    },
    "legendFontColor": {
        "en": "font color",
        "de": "Schriftfarbe",
        "ru": "Цвет шрифта",
        "pt": "cor da fonte",
        "nl": "letterkleur",
        "fr": "couleur de la police",
        "it": "colore del carattere",
        "es": "color de fuente",
        "pl": "kolor czcionki",
        "zh-cn": "字体颜色"
    },
    "legendFontFamily": {
        "en": "font",
        "de": "Schriftart",
        "ru": "шрифт",
        "pt": "Fonte",
        "nl": "doopvont",
        "fr": "Police de caractère",
        "it": "font",
        "es": "fuente",
        "pl": "czcionka",
        "zh-cn": "字形"
    },
    "legendFontSize": {
        "en": "font size",
        "de": "Schriftgröße",
        "ru": "размер шрифта",
        "pt": "tamanho da fonte",
        "nl": "lettertypegrootte",
        "fr": "taille de police",
        "it": "dimensione del font",
        "es": "tamaño de fuente",
        "pl": "rozmiar czcionki",
        "zh-cn": "字体大小"
    },
    "legendBoxWidth": {
        "en": "legend box width",
        "de": "Breite der Legendenbox",
        "ru": "ширина легенды",
        "pt": "largura da caixa da legenda",
        "nl": "legenda vakbreedte",
        "fr": "largeur de la boîte de légende",
        "it": "larghezza della scatola della legenda",
        "es": "ancho del cuadro de leyenda",
        "pl": "szerokość pudełka z legendami",
        "zh-cn": "图例框宽度"
    },
    "legendPointStyle": {
        "en": "activate legend point layout",
        "de": "Legendenpunktlayout aktivieren",
        "ru": "активировать расположение точек легенды",
        "pt": "ativar o layout do ponto de legenda",
        "nl": "activeer legende punt layout",
        "fr": "activer la disposition des points de légende",
        "it": "attiva il layout del punto legenda",
        "es": "activar el diseño del punto de leyenda",
        "pl": "aktywuj układ punktu legendy",
        "zh-cn": "激活图例点布局"
    },
    "showTooltipshowTooltip": {
        "en": "show Tooltip",
        "de": "Tooltip anzeigen",
        "ru": "показать подсказку",
        "pt": "show Tooltip",
        "nl": "tooltip weergeven",
        "fr": "afficher l'info-bulle",
        "it": "mostra tooltip",
        "es": "muestre la información sobre herramientas",
        "pl": "pokaż etykietkę",
        "zh-cn": "显示工具提示"
    },
    "tooltipBackgroundColor": {
        "en": "background color",
        "de": "Hintergrundfarbe",
        "ru": "фоновый цвет",
        "pt": "cor de fundo",
        "nl": "Achtergrond kleur",
        "fr": "Couleur de l'arrière plan",
        "it": "colore di sfondo",
        "es": "color de fondo",
        "pl": "kolor tła",
        "zh-cn": "背景颜色"
    },
    "tooltipArrowSize": {
        "en": "arrow size",
        "de": "Pfeilgröße",
        "ru": "Размер стрелки",
        "pt": "tamanho da seta",
        "nl": "pijl grootte",
        "fr": "taille de la flèche",
        "it": "dimensione della freccia",
        "es": "tamaño de la flecha",
        "pl": "wielkość strzały",
        "zh-cn": "箭头大小"
    },
    "tooltipDistanceToBar": {
        "en": "tooltip distance",
        "de": "Tooltip-Abstand",
        "ru": "расстояние до всплывающей подсказки",
        "pt": "distância da dica",
        "nl": "tooltip afstand",
        "fr": "distance de l'info-bulle",
        "it": "distanza della descrizione comandi",
        "es": "distancia de información sobre herramientas",
        "pl": "odległość etykietki",
        "zh-cn": "工具提示距离"
    },
    "tooltipBoxRadius": {
        "en": "border radius",
        "de": "Rahmenradius",
        "ru": "радиус границы",
        "pt": "raio da borda",
        "nl": "grensradius",
        "fr": "rayon de la frontière",
        "it": "raggio di frontiera",
        "es": "radio de borde",
        "pl": "promień graniczny",
        "zh-cn": "边界半径"
    },
    "tooltipShowColorBox": {
        "en": "show color box",
        "de": "Farbfeld anzeigen",
        "ru": "показать коробку цвета",
        "pt": "mostre a caixa de cor",
        "nl": "kleurvak weergeven",
        "fr": "afficher la boîte de couleur",
        "it": "mostra la scatola dei colori",
        "es": "mostrar cuadro de color",
        "pl": "pokaż pole koloru",
        "zh-cn": "显示彩盒"
    },
    "tooltipXpadding": {
        "en": "x-padding",
        "de": "x-padding",
        "ru": "х-обивка",
        "pt": "x-padding",
        "nl": "x-padding",
        "fr": "X-padding",
        "it": "x-padding",
        "es": "relleno de x",
        "pl": "x-padding",
        "zh-cn": "填充"
    },
    "tooltipYpadding": {
        "en": "y-padding",
        "de": "Y-Polsterung",
        "ru": "у-набивка",
        "pt": "estofamento em y",
        "nl": "y-padding",
        "fr": "y-padding",
        "it": "y-padding",
        "es": "relleno en y",
        "pl": "y-padding",
        "zh-cn": "填充"
    },
    "tooltipTitleFontColor": {
        "en": "title font color",
        "de": "Schriftfarbe des Titels",
        "ru": "цвет шрифта заголовка",
        "pt": "cor da fonte do título",
        "nl": "titel lettertypekleur",
        "fr": "couleur de police du titre",
        "it": "colore del carattere del titolo",
        "es": "color de fuente del título",
        "pl": "kolor czcionki tytułu",
        "zh-cn": "标题字体颜色"
    },
    "tooltipTitleFontFamily": {
        "en": "font title",
        "de": "Schriftart des Titels",
        "ru": "название шрифта",
        "pt": "título da fonte",
        "nl": "lettertype titel",
        "fr": "titre de la police",
        "it": "titolo del carattere",
        "es": "título de fuente",
        "pl": "tytuł czcionki",
        "zh-cn": "字体标题"
    },
    "tooltipTitleFontSize": {
        "en": "title font size",
        "de": "Schriftgröße des Titels",
        "ru": "размер шрифта заголовка",
        "pt": "tamanho da fonte do título",
        "nl": "titel lettergrootte",
        "fr": "titre police taille",
        "it": "dimensione del carattere del titolo",
        "es": "tamaño de fuente del título",
        "pl": "rozmiar czcionki tytułu",
        "zh-cn": "标题字体大小"
    },
    "tooltipTitleMarginBottom": {
        "en": "title distance to bottom",
        "de": "Titelabstand nach unten",
        "ru": "заголовок расстояние до дна",
        "pt": "distância do título até o fundo",
        "nl": "titel afstand tot onderkant",
        "fr": "titre distance au bas",
        "it": "distanza del titolo dal basso",
        "es": "distancia del título al fondo",
        "pl": "odległość tytułu do dołu",
        "zh-cn": "标题到底部的距离"
    },
    "tooltipBodyFontColor": {
        "en": "text font color",
        "de": "Text Schriftfarbe",
        "ru": "цвет шрифта текста",
        "pt": "cor da fonte do texto",
        "nl": "tekst lettertype kleur",
        "fr": "couleur de police de texte",
        "it": "colore del carattere del testo",
        "es": "color de fuente del texto",
        "pl": "kolor czcionki tekstu",
        "zh-cn": "文字字体颜色"
    },
    "tooltipBodyFontFamily": {
        "en": "text font",
        "de": "Text Schriftart",
        "ru": "шрифт текста",
        "pt": "fonte de texto",
        "nl": "tekst lettertype",
        "fr": "police de texte",
        "it": "font di testo",
        "es": "tipografía del texto",
        "pl": "czcionka tekstowa",
        "zh-cn": "文字字型"
    },
    "tooltipBodyFontSize": {
        "en": "text font size",
        "de": "Text Schriftgröße",
        "ru": "размер шрифта текста",
        "pt": "tamanho da fonte do texto",
        "nl": "tekst lettergrootte",
        "fr": "taille de la police du texte",
        "it": "dimensione del carattere del testo",
        "es": "tamaño de fuente del texto",
        "pl": "rozmiar czcionki tekstu",
        "zh-cn": "文字字型大小"
    },
    "tooltipBodyAppend": {
        "en": "text appendix",
        "de": "Text Anhang",
        "ru": "текстовое приложение",
        "pt": "apêndice de texto",
        "nl": "tekst bijlage",
        "fr": "annexe de texte",
        "it": "appendice di testo",
        "es": "apéndice de texto",
        "pl": "załącznik tekstowy",
        "zh-cn": "文字附录"
    },
    "tooltipValueMaxDecimals": {
        "en": "text maximal decimals",
        "de": "Text maximal Dezimalstellen",
        "ru": "текст максимальные десятичные дроби",
        "pt": "decimais máximos de texto",
        "nl": "maximale tekst decimalen",
        "fr": "texte maximal décimal",
        "it": "decimali massimi del testo",
        "es": "decimales máximos de texto",
        "pl": "tekstowe liczby dziesiętne",
        "zh-cn": "文字最大小数"
    },
    "dataColor": {
        "en": "data color",
        "de": "Datenfarbe",
        "ru": "цвет данных",
        "pt": "cor dos dados",
        "nl": "gegevens kleur",
        "fr": "couleur des données",
        "it": "colore dei dati",
        "es": "color de datos",
        "pl": "kolor danych",
        "zh-cn": "资料颜色"
    },
    "valueTextColor": {
        "en": "value text color",
        "de": "Wert Textfarbe",
        "ru": "значение цвета текста",
        "pt": "valor cor do texto",
        "nl": "waarde tekstkleur",
        "fr": "valeur couleur du texte",
        "it": "valore del colore del testo",
        "es": "valor del color del texto",
        "pl": "wartość koloru tekstu",
        "zh-cn": "值文字颜色"
    },
    "labelValueAppend": {
        "en": "value text appendix",
        "de": "Wert Textanhang",
        "ru": "текстовое приложение значения",
        "pt": "apêndice de texto com valor",
        "nl": "waarde tekst bijlage",
        "fr": "annexe texte valeur",
        "it": "appendice testo valore",
        "es": "apéndice de texto de valor",
        "pl": "tekst wartości dodatku",
        "zh-cn": "值文本附录"
    },
    "switch": {
        "en": "switch",
        "de": "Schalter",
        "ru": "переключатель",
        "pt": "interruptor",
        "nl": "schakelaar",
        "fr": "commutateur",
        "it": "interruttore",
        "es": "cambiar",
        "pl": "przełącznik",
        "zh-cn": "开关"
    },
    "checkbox": {
        "en": "checkbox",
        "de": "Kontrollkästchen",
        "ru": "флажок",
        "pt": "caixa de seleção",
        "nl": "checkbox",
        "fr": "case à cocher",
        "it": "casella di controllo",
        "es": "caja",
        "pl": "pole wyboru",
        "zh-cn": "复选框"
    },
    "group_labels": {
        "en": "labels",
        "de": "Beschriftungen",
        "ru": "этикетки",
        "pt": "etiquetas",
        "nl": "labels",
        "fr": "Étiquettes",
        "it": "etichette",
        "es": "etiquetas",
        "pl": "etykiety",
        "zh-cn": "标签"
    },
    "group_yAxisLayout": {
        "en": "y axis layout",
        "de": "y-Achsen Layout",
        "ru": "макет оси Y",
        "pt": "layout do eixo y",
        "nl": "y-aslay-out",
        "fr": "Disposition en Y",
        "it": "layout dell'asse y",
        "es": "diseño del eje y",
        "pl": "układ osi y",
        "zh-cn": "y轴布局"
    },
    "group_xAxisLayout": {
        "en": "x axis layout",
        "de": "X-Achsen Layout",
        "ru": "макет оси X",
        "pt": "layout do eixo x",
        "nl": "x asindeling",
        "fr": "disposition des axes x",
        "it": "layout dell'asse x",
        "es": "diseño del eje x",
        "pl": "układ osi x",
        "zh-cn": "x轴布局"
    },
    "backgroundColor": {
        "en": "background color",
        "de": "Hintergrundfarbe",
        "ru": "фоновый цвет",
        "pt": "cor de fundo",
        "nl": "Achtergrond kleur",
        "fr": "Couleur de l'arrière plan",
        "it": "colore di sfondo",
        "es": "color de fondo",
        "pl": "kolor tła",
        "zh-cn": "背景颜色"
    },
    "colorScheme": {
        "en": "color Scheme",
        "de": "Farbschema",
        "ru": "Цветовая схема",
        "pt": "esquema de cores",
        "nl": "kleurenschema",
        "fr": "Schéma de couleur",
        "it": "combinazione di colori",
        "es": "esquema de colores",
        "pl": "schemat kolorów",
        "zh-cn": "配色方案"
    },
    "group_labels": {
        "en": "labels",
        "de": "Beschriftungen",
        "ru": "этикетки",
        "pt": "etiquetas",
        "nl": "labels",
        "fr": "Étiquettes",
        "it": "etichette",
        "es": "etiquetas",
        "pl": "etykiety",
        "zh-cn": "标签"
    },
    "yAxisPosition": {
        "en": "axis position",
        "de": "Achsposition",
        "ru": "положение оси",
        "pt": "posição do eixo",
        "nl": "as positie",
        "fr": "position de l'axe",
        "it": "posizione dell'asse",
        "es": "posición del eje",
        "pl": "pozycja osi",
        "zh-cn": "轴位置"
    },
    "xAxisPosition": {
        "en": "axis position",
        "de": "Achsposition",
        "ru": "положение оси",
        "pt": "posição do eixo",
        "nl": "as positie",
        "fr": "position de l'axe",
        "it": "posizione dell'asse",
        "es": "posición del eje",
        "pl": "pozycja osi",
        "zh-cn": "轴位置"
    },
    "yAxisTitleColor": {
        "en": "title",
        "de": "Titel",
        "ru": "заглавие",
        "pt": "título",
        "nl": "titel",
        "fr": "Titre",
        "it": "titolo",
        "es": "título",
        "pl": "tytuł",
        "zh-cn": "标题"
    },
    "xAxisTitleColor": {
        "en": "title",
        "de": "Titel",
        "ru": "заглавие",
        "pt": "título",
        "nl": "titel",
        "fr": "Titre",
        "it": "titolo",
        "es": "título",
        "pl": "tytuł",
        "zh-cn": "标题"
    },
    "yAxisTitleFontFamily": {
        "en": "title font",
        "de": "Titel Schriftart",
        "ru": "шрифт заголовка",
        "pt": "fonte do título",
        "nl": "Titel lettertype",
        "fr": "police de titre",
        "it": "carattere del titolo",
        "es": "fuente del titulo",
        "pl": "czcionka tytułu",
        "zh-cn": "标题字体"
    }
    ,
    "xAxisTitleFontFamily": {
        "en": "title font",
        "de": "Titel Schriftart",
        "ru": "шрифт заголовка",
        "pt": "fonte do título",
        "nl": "Titel lettertype",
        "fr": "police de titre",
        "it": "carattere del titolo",
        "es": "fuente del titulo",
        "pl": "czcionka tytułu",
        "zh-cn": "标题字体"
    },
    "yAxisTitleFontSize": {
        "en": "title font size",
        "de": "Titel Schriftgröße",
        "ru": "размер шрифта заголовка",
        "pt": "tamanho da fonte do título",
        "nl": "titel lettergrootte",
        "fr": "titre police taille",
        "it": "dimensione del carattere del titolo",
        "es": "tamaño de fuente del título",
        "pl": "rozmiar czcionki tytułu",
        "zh-cn": "标题字体大小"
    }
    ,
    "xAxisTitleFontSize": {
        "en": "title font size",
        "de": "Titel Schriftgröße",
        "ru": "размер шрифта заголовка",
        "pt": "tamanho da fonte do título",
        "nl": "titel lettergrootte",
        "fr": "titre police taille",
        "it": "dimensione del carattere del titolo",
        "es": "tamaño de fuente del título",
        "pl": "rozmiar czcionki tytułu",
        "zh-cn": "标题字体大小"
    },
    "yAxisTitleColor": {
        "en": "title font color",
        "de": "Ttiel Schriftfarbe",
        "ru": "цвет шрифта заголовка",
        "pt": "cor da fonte do título",
        "nl": "titel lettertypekleur",
        "fr": "couleur de police du titre",
        "it": "colore del carattere del titolo",
        "es": "color de fuente del título",
        "pl": "kolor czcionki tytułu",
        "zh-cn": "标题字体颜色"
    },
    "xAxisTitleColor": {
        "en": "title font color",
        "de": "Ttiel Schriftfarbe",
        "ru": "цвет шрифта заголовка",
        "pt": "cor da fonte do título",
        "nl": "titel lettertypekleur",
        "fr": "couleur de police du titre",
        "it": "colore del carattere del titolo",
        "es": "color de fuente del título",
        "pl": "kolor czcionki tytułu",
        "zh-cn": "标题字体颜色"
    },
    "yAxisValueLabelColor": {
        "en": "axis label color",
        "de": "Achsenbeschriftung Schriftfarbe",
        "ru": "цвет метки оси",
        "pt": "cor da etiqueta do eixo",
        "nl": "aslabel kleur",
        "fr": "couleur d'étiquette d'axe",
        "it": "colore etichetta asse",
        "es": "color de etiqueta del eje",
        "pl": "kolor etykiety osi",
        "zh-cn": "轴标签颜色"
    }
    ,
    "xAxisValueLabelColor": {
        "en": "axis label color",
        "de": "Achsenbeschriftung Schriftfarbe",
        "ru": "цвет метки оси",
        "pt": "cor da etiqueta do eixo",
        "nl": "aslabel kleur",
        "fr": "couleur d'étiquette d'axe",
        "it": "colore etichetta asse",
        "es": "color de etiqueta del eje",
        "pl": "kolor etykiety osi",
        "zh-cn": "轴标签颜色"
    },
    "yAxisValueFontFamily": {
        "en": "axis label font",
        "de": "Achsenbeschriftung Schriftart",
        "ru": "шрифт метки оси",
        "pt": "fonte de rótulo do eixo",
        "nl": "aslabel lettertype",
        "fr": "police d'étiquette d'axe",
        "it": "carattere etichetta asse",
        "es": "fuente de etiqueta de eje",
        "pl": "czcionka etykiety osi",
        "zh-cn": "轴标签字体"
    }
    ,
    "xAxisValueFontFamily": {
        "en": "axis label font",
        "de": "Achsenbeschriftung Schriftart",
        "ru": "шрифт метки оси",
        "pt": "fonte de rótulo do eixo",
        "nl": "aslabel lettertype",
        "fr": "police d'étiquette d'axe",
        "it": "carattere etichetta asse",
        "es": "fuente de etiqueta de eje",
        "pl": "czcionka etykiety osi",
        "zh-cn": "轴标签字体"
    },
    "yAxisValueFontSize": {
        "en": "axis label font size",
        "de": "Achsenbeschriftung Schriftgröße",
        "ru": "размер шрифта метки оси",
        "pt": "tamanho da fonte do rótulo do eixo",
        "nl": "aslabel lettergrootte",
        "fr": "taille de la police de l'étiquette d'axe",
        "it": "dimensione carattere etichetta asse",
        "es": "tamaño de fuente de la etiqueta del eje",
        "pl": "rozmiar czcionki etykiety osi",
        "zh-cn": "轴标签字体大小"
    },
    "xAxisValueFontSize": {
        "en": "axis label font size",
        "de": "Achsenbeschriftung Schriftgröße",
        "ru": "размер шрифта метки оси",
        "pt": "tamanho da fonte do rótulo do eixo",
        "nl": "aslabel lettergrootte",
        "fr": "taille de la police de l'étiquette d'axe",
        "it": "dimensione carattere etichetta asse",
        "es": "tamaño de fuente de la etiqueta del eje",
        "pl": "rozmiar czcionki etykiety osi",
        "zh-cn": "轴标签字体大小"
    },
    "yAxisValueDistanceToAxis": {
        "en": "axis label distance",
        "de": "Achsenbeschriftung Abstand",
        "ru": "расстояние между метками оси",
        "pt": "distância da etiqueta do eixo",
        "nl": "aslabelafstand",
        "fr": "distance entre les axes",
        "it": "distanza dell'etichetta dell'asse",
        "es": "distancia de etiqueta del eje",
        "pl": "odległość etykiety osi",
        "zh-cn": "轴标签距离"
    },
    "xAxisValueDistanceToAxis": {
        "en": "axis label distance",
        "de": "Achsenbeschriftung Abstand",
        "ru": "расстояние между метками оси",
        "pt": "distância da etiqueta do eixo",
        "nl": "aslabelafstand",
        "fr": "distance entre les axes",
        "it": "distanza dell'etichetta dell'asse",
        "es": "distancia de etiqueta del eje",
        "pl": "odległość etykiety osi",
        "zh-cn": "轴标签距离"
    },
    "yAxisShowAxis": {
        "en": "show axis",
        "de": "Achse anzeigen",
        "ru": "показать ось",
        "pt": "mostrar eixo",
        "nl": "as weergeven",
        "fr": "montrer l'axe",
        "it": "mostra asse",
        "es": "mostrar eje",
        "pl": "pokaż oś",
        "zh-cn": "显示轴"
    },
    "xAxisShowAxis": {
        "en": "show axis",
        "de": "Achse anzeigen",
        "ru": "показать ось",
        "pt": "mostrar eixo",
        "nl": "as weergeven",
        "fr": "montrer l'axe",
        "it": "mostra asse",
        "es": "mostrar eje",
        "pl": "pokaż oś",
        "zh-cn": "显示轴"
    },
    "yAxisShowAxisLabels": {
        "en": "show axis label",
        "de": "Achsenbeschriftung anzeigen",
        "ru": "показать метку оси",
        "pt": "mostrar etiqueta do eixo",
        "nl": "aslabel weergeven",
        "fr": "affichez l'étiquette",
        "it": "mostra l'etichetta dell'asse",
        "es": "mostrar etiqueta del eje",
        "pl": "pokaż etykietę osi",
        "zh-cn": "显示轴标签"
    },
    "xAxisShowAxisLabels": {
        "en": "show axis label",
        "de": "Achsenbeschriftung anzeigen",
        "ru": "показать метку оси",
        "pt": "mostrar etiqueta do eixo",
        "nl": "aslabel weergeven",
        "fr": "affichez l'étiquette",
        "it": "mostra l'etichetta dell'asse",
        "es": "mostrar etiqueta del eje",
        "pl": "pokaż etykietę osi",
        "zh-cn": "显示轴标签"
    },
    "yAxisShowGridLines": {
        "en": "show gridlines",
        "de": "Gitterlinien anzeigen",
        "ru": "показать линии сетки",
        "pt": "mostrar linhas de grade",
        "nl": "rasterlijnen weergeven",
        "fr": "montrer les lignes de la grille",
        "it": "mostra linee della griglia",
        "es": "mostrar cuadrículas",
        "pl": "pokaż linie siatki",
        "zh-cn": "显示网格线"
    },
    "xAxisShowGridLines": {
        "en": "show gridlines",
        "de": "Gitterlinien anzeigen",
        "ru": "показать линии сетки",
        "pt": "mostrar linhas de grade",
        "nl": "rasterlijnen weergeven",
        "fr": "montrer les lignes de la grille",
        "it": "mostra linee della griglia",
        "es": "mostrar cuadrículas",
        "pl": "pokaż linie siatki",
        "zh-cn": "显示网格线"
    },
    "yAxisGridLinesColor": {
        "en": "gridlines color",
        "de": "Farbe der Gitternetzlinien",
        "ru": "цвет линий сетки",
        "pt": "cor das linhas de grade",
        "nl": "rasterlijnen kleur",
        "fr": "couleur de la grille",
        "it": "colore della griglia",
        "es": "color de cuadrícula",
        "pl": "kolor linii siatki",
        "zh-cn": "网格线颜色"
    },
    "xAxisGridLinesColor": {
        "en": "gridlines color",
        "de": "Farbe der Gitternetzlinien",
        "ru": "цвет линий сетки",
        "pt": "cor das linhas de grade",
        "nl": "rasterlijnen kleur",
        "fr": "couleur de la grille",
        "it": "colore della griglia",
        "es": "color de cuadrícula",
        "pl": "kolor linii siatki",
        "zh-cn": "网格线颜色"
    },
    "yAxisGridLinesWitdh": {
        "en": "gridlines width",
        "de": "Breite der Gitternetzlinien",
        "ru": "ширина линий сетки",
        "pt": "largura das linhas de grade",
        "nl": "rasterlijnen breedte",
        "fr": "largeur de la grille",
        "it": "larghezza della griglia",
        "es": "ancho de cuadrículas",
        "pl": "szerokość linii siatki",
        "zh-cn": "网格线宽度"
    },
    "xAxisGridLinesWitdh": {
        "en": "gridlines width",
        "de": "Breite der Gitternetzlinien",
        "ru": "ширина линий сетки",
        "pt": "largura das linhas de grade",
        "nl": "rasterlijnen breedte",
        "fr": "largeur de la grille",
        "it": "larghezza della griglia",
        "es": "ancho de cuadrículas",
        "pl": "szerokość linii siatki",
        "zh-cn": "网格线宽度"
    },
    "yAxisShowTicks": {
        "en": "show axis intervals",
        "de": "Achsenintervalle anzeigen",
        "ru": "показать интервалы оси",
        "pt": "mostrar intervalos do eixo",
        "nl": "asintervallen weergeven",
        "fr": "afficher les intervalles d'axe",
        "it": "mostra gli intervalli degli assi",
        "es": "mostrar intervalos de eje",
        "pl": "pokaż przedziały osi",
        "zh-cn": "显示轴间隔"
    },
    "xAxisShowTicks": {
        "en": "show axis intervals",
        "de": "Achsenintervalle anzeigen",
        "ru": "показать интервалы оси",
        "pt": "mostrar intervalos do eixo",
        "nl": "asintervallen weergeven",
        "fr": "afficher les intervalles d'axe",
        "it": "mostra gli intervalli degli assi",
        "es": "mostrar intervalos de eje",
        "pl": "pokaż przedziały osi",
        "zh-cn": "显示轴间隔"
    },
    "yAxisTickLength": {
        "en": "axis intervals line length",
        "de": "Achsenintervalle Linienlänge",
        "ru": "длина линии интервалов оси",
        "pt": "intervalo da linha comprimento da linha",
        "nl": "asintervallen lijnlengte",
        "fr": "longueur des lignes",
        "it": "lunghezza dell'asse intervalli di linea",
        "es": "intervalos de eje longitud de línea",
        "pl": "długość linii interwałów osi",
        "zh-cn": "轴间隔线长"
    },
    "xAxisTickLength": {
        "en": "axis intervals line length",
        "de": "Achsenintervalle Linienlänge",
        "ru": "длина линии интервалов оси",
        "pt": "intervalo da linha comprimento da linha",
        "nl": "asintervallen lijnlengte",
        "fr": "longueur des lignes",
        "it": "lunghezza dell'asse intervalli di linea",
        "es": "intervalos de eje longitud de línea",
        "pl": "długość linii interwałów osi",
        "zh-cn": "轴间隔线长"
    },
    "group_oids": {
        "en": "datasets",
        "de": "Datensätze",
        "ru": "Наборы данных",
        "pt": "conjuntos de dados",
        "nl": "datasets",
        "fr": "jeux de données",
        "it": "dataset",
        "es": "conjuntos de datos",
        "pl": "zestawy danych",
        "zh-cn": "资料集"
    }
};
