/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "myColor": {
        "en": "myColor",
        "de": "meineColor",
        "ru": "Мой цвет",
        "pt": "minhaCor",
        "nl": "mijnKleur",
        "fr": "maCouleur",
        "it": "mioColore",
        "es": "miColor",
        "pl": "mójKolor",
        "zh-cn": "我的颜色"
    },
    "myColor_tooltip": {
        "en": "Description of\nmyColor",
        "de": "Beschreibung von\nmyColor",
        "ru": "Описание\nmyColor",
        "pt": "Descrição de\nmyColor",
        "nl": "Beschrijving van\nmyColor",
        "fr": "Description de\nmyColor",
        "it": "Descrizione di\nmyColor",
        "es": "Descripción de\nmyColor",
        "pl": "Opis\nmyColor",
        "zh-cn": "\nmyColor的描述"
    },
    "htmlText": {
        "en": "htmlText",
        "de": "htmlText",
        "ru": "htmlText",
        "pt": "htmlText",
        "nl": "htmlText",
        "fr": "htmlText",
        "it": "htmlText",
        "es": "htmlText",
        "pl": "htmlText",
        "zh-cn": "htmlText"
    },
    "group_extraMyset": {
        "en": "extraMyset",
        "de": "extraMyset",
        "ru": "extraMyset",
        "pt": "extraMyset",
        "nl": "extraMyset",
        "fr": "extraMyset",
        "it": "extraMyset",
        "es": "extraMyset",
        "pl": "extraMyset",
        "zh-cn": "extraMyset"
    },
    "extraAttr": {
        "en": "extraAttr",
        "de": "extraAttr",
        "ru": "extraAttr",
        "pt": "extraAttr",
        "nl": "extraAttr",
        "fr": "extraAttr",
        "it": "extraAttr",
        "es": "extraAttr",
        "pl": "extraAttr",
        "zh-cn": "extraAttr"
    },
    "Instance": {
        "en": "Instance",
        "de": "Instanz",
        "ru": "Инстанция",
        "pt": "Instância",
        "nl": "Instantie",
        "fr": "Instance",
        "it": "Esempio",
        "es": "Instancia",
        "pl": "Instancja",
        "zh-cn": "例"
    },
    "label": {
        "en": "label",
        "de": "Beschriftung",
        "ru": "этикетка",
        "pt": "rótulo",
        "nl": "label",
        "fr": "étiquette",
        "it": "etichetta",
        "es": "etiqueta",
        "pl": "etykieta",
        "zh-cn": "标签"
    },
    "buttonStyle": {
        "en": "button style",
        "de": "Schaltflächenstil",
        "ru": "стиль кнопки",
        "pt": "estilo de botão",
        "nl": "knopstijl",
        "fr": "style de bouton",
        "it": "stile pulsante",
        "es": "estilo de botón",
        "pl": "styl przycisku",
        "zh-cn": "按钮样式"
    },
    "titleLayout": {
        "en": "title font size",
        "de": "Schriftgröße des Titels",
        "ru": "размер шрифта заголовка",
        "pt": "tamanho da fonte do título",
        "nl": "titel lettergrootte",
        "fr": "titre police taille",
        "it": "dimensione del carattere del titolo",
        "es": "tamaño de fuente del título",
        "pl": "rozmiar czcionki tytułu",
        "zh-cn": "标题字体大小"
    },
    "subtitleLayout": {
        "en": "subtitle font size",
        "de": "Schriftgröße für Untertitel",
        "ru": "размер шрифта субтитров",
        "pt": "tamanho da fonte da legenda",
        "nl": "ondertitel lettergrootte",
        "fr": "taille de la police des sous-titres",
        "it": "dimensione del carattere dei sottotitoli",
        "es": "tamaño de fuente de subtítulos",
        "pl": "rozmiar czcionki napisów",
        "zh-cn": "字幕字体大小"
    },
    "htmlLayout": {
        "en": "text style",
        "de": "Textstil",
        "ru": "стиль текста",
        "pt": "estilo de texto",
        "nl": "tekststijl",
        "fr": "style de texte",
        "it": "stile del testo",
        "es": "estilo de texto",
        "pl": "styl tekstu",
        "zh-cn": "文字样式"
    },
    "group_label": {
        "en": "labeling",
        "de": "Beschriftung",
        "ru": "маркировка",
        "pt": "marcação",
        "nl": "labeling",
        "fr": "étiquetage",
        "it": "etichettatura",
        "es": "etiquetado",
        "pl": "etykietowanie",
        "zh-cn": "标签"
    },
    "labelFalse": {
        "en": "label",
        "de": "Beschriftung",
        "ru": "этикетка",
        "pt": "rótulo",
        "nl": "label",
        "fr": "étiquette",
        "it": "etichetta",
        "es": "etiqueta",
        "pl": "etykieta",
        "zh-cn": "标签"
    },
    "labelTrue": {
        "en": "active label",
        "de": "aktive Beschriftung",
        "ru": "активная метка",
        "pt": "etiqueta ativa",
        "nl": "actief label",
        "fr": "étiquette active",
        "it": "etichetta attiva",
        "es": "etiqueta activa",
        "pl": "aktywna etykieta",
        "zh-cn": "活动标签"
    },
    "labelColorFalse": {
        "en": "label color",
        "de": "Beschriftungsfarbe",
        "ru": "цвет этикетки",
        "pt": "cor da etiqueta",
        "nl": "label kleur",
        "fr": "couleur de l'étiquette",
        "it": "colore dell'etichetta",
        "es": "color de etiqueta",
        "pl": "kolor etykiety",
        "zh-cn": "标签颜色"
    },
    "labelColorTrue": {
        "en": "active label color",
        "de": "aktive Beschriftungsfarbe",
        "ru": "активный цвет метки",
        "pt": "cor da etiqueta ativa",
        "nl": "actieve labelkleur",
        "fr": "couleur de l'étiquette active",
        "it": "colore etichetta attiva",
        "es": "color de etiqueta activa",
        "pl": "aktywny kolor etykiety",
        "zh-cn": "活动标签颜色"
    },
    "showValueLabel": {
        "en": "show value",
        "de": "Wert anzeigen",
        "ru": "показать значение",
        "pt": "mostrar valor",
        "nl": "toon waarde",
        "fr": "montrer la valeur",
        "it": "mostra valore",
        "es": "mostrar valor",
        "pl": "pokaż wartość",
        "zh-cn": "显示价值"
    },
    "valueLabelUnit": {
        "en": "unit",
        "de": "Einheit",
        "ru": "единица измерения",
        "pt": "unidade",
        "nl": "eenheid",
        "fr": "unité",
        "it": "unità",
        "es": "unidad",
        "pl": "jednostka",
        "zh-cn": "单元"
    },
    "valueMaxDecimals": {
        "en": "decimal points",
        "de": "Kommastellen",
        "ru": "десятичные точки",
        "pt": "pontos decimais",
        "nl": "decimale punten",
        "fr": "points décimaux",
        "it": "punti decimali",
        "es": "puntos decimales",
        "pl": "Punkty dziesiętne",
        "zh-cn": "小数点"
    },
    "valuePosition": {
        "en": "display position",
        "de": "Anzeigeposition",
        "ru": "положение дисплея",
        "pt": "posição de exibição",
        "nl": "weergave positie",
        "fr": "position d'affichage",
        "it": "posizione di visualizzazione",
        "es": "posición de visualización",
        "pl": "pozycja wyświetlania",
        "zh-cn": "显示位置"
    },
    "inside": {
        "en": "inside",
        "de": "innerhalb",
        "ru": "внутри",
        "pt": "dentro",
        "nl": "binnen",
        "fr": "à l'intérieur",
        "it": "dentro",
        "es": "dentro",
        "pl": "wewnątrz",
        "zh-cn": "内"
    },
    "outside": {
        "en": "outside",
        "de": "außerhalb",
        "ru": "снаружи",
        "pt": "lado de fora",
        "nl": "buiten",
        "fr": "à l'extérieur",
        "it": "al di fuori",
        "es": "fuera de",
        "pl": "na zewnątrz",
        "zh-cn": "外"
    },
    "valueLabelWidth": {
        "en": "distance label",
        "de": "Abstand Beschriftung",
        "ru": "метка расстояния",
        "pt": "etiqueta de distância",
        "nl": "afstandslabel",
        "fr": "étiquette de distance",
        "it": "etichetta della distanza",
        "es": "etiqueta de distancia",
        "pl": "etykieta odległości",
        "zh-cn": "距离标签"
    },
    "labelFalsePrepend": {
        "en": "prepend label",
        "de": "Beschriftung vorangestellt",
        "ru": "предварительно метка",
        "pt": "Anexar etiqueta",
        "nl": "label voorzetten",
        "fr": "pré-étiquette",
        "it": "anteporre etichetta",
        "es": "etiqueta de anteponer",
        "pl": "dodaj etykietę",
        "zh-cn": "前置标签"
    },
    "labelTruePrepend": {
        "en": "active prepend label",
        "de": "aktive Beschriftung vorangestellt",
        "ru": "активная метка prepend",
        "pt": "etiqueta de prefixação ativa",
        "nl": "actief prepend-label",
        "fr": "étiquette active de début",
        "it": "etichetta prepend attiva",
        "es": "etiqueta de anteponer activa",
        "pl": "aktywna etykieta poprzedzająca",
        "zh-cn": "有效的前置标签"
    },
    "labelFalseAppend": {
        "en": "append label",
        "de": "Beschriftung nachgestellt",
        "ru": "добавить ярлык",
        "pt": "acrescentar etiqueta",
        "nl": "label toevoegen",
        "fr": "apposer une étiquette",
        "it": "etichetta append",
        "es": "agregar etiqueta",
        "pl": "dołącz etykietę",
        "zh-cn": "附加标签"
    },
    "labelTrueAppend": {
        "en": "active append label",
        "de": "aktive Beschriftung nachgestellt",
        "ru": "метка активного добавления",
        "pt": "etiqueta de acréscimo ativo",
        "nl": "actief toevoeglabel",
        "fr": "étiquette active",
        "it": "etichetta append attiva",
        "es": "etiqueta de adición activa",
        "pl": "aktywna etykieta dołączania",
        "zh-cn": "活动的附加标签"
    },
    "showMarkers": {
        "en": "show Markers",
        "de": "Markierungen anzeigen",
        "ru": "показать маркеры",
        "pt": "mostrar marcadores",
        "nl": "markeringen weergeven",
        "fr": "montrer les marqueurs",
        "it": "mostra marcatori",
        "es": "mostrar marcadores",
        "pl": "pokaż Markery",
        "zh-cn": "显示标记"
    },
    "valueLabelMin": {
        "en": "label for value less than min",
        "de": "Beschriftung für Wert kleiner als min",
        "ru": "метка для значения меньше мин",
        "pt": "rótulo para valor menor que min",
        "nl": "label voor waarde minder dan min",
        "fr": "étiquette pour valeur inférieure à min",
        "it": "etichetta per valore inferiore a min",
        "es": "etiqueta para valor menor que min",
        "pl": "etykieta dla wartości mniejszej niż min",
        "zh-cn": "标签值小于min"
    },
    "valueLabelMax": {
        "en": "label for value greater than max",
        "de": "Beschriftung für Wert größer als max",
        "ru": "метка для значения больше, чем max",
        "pt": "rótulo para valor maior que max",
        "nl": "label voor waarde groter dan max",
        "fr": "étiquette pour valeur supérieure à max",
        "it": "etichetta per valore maggiore di max",
        "es": "etiqueta para valor mayor que max",
        "pl": "etykieta dla wartości większej niż maks",
        "zh-cn": "标签值大于最大值"
    },
    "labelClickActive": {
        "en": "activate label click",
        "de": "Beschriftungs-Klick aktivieren",
        "ru": "активировать ярлык нажмите",
        "pt": "ativar clique de etiqueta",
        "nl": "activeer label klik",
        "fr": "activer l'étiquette cliquer",
        "it": "attiva il clic sull'etichetta",
        "es": "activar clic de etiqueta",
        "pl": "aktywuj kliknięcie etykiety",
        "zh-cn": "激活标签点击"
    },
    "group_icon": {
        "en": "icon",
        "de": "Symbol",
        "ru": "икона",
        "pt": "ícone",
        "nl": "icoon",
        "fr": "icône",
        "it": "icona",
        "es": "icono",
        "pl": "Ikona",
        "zh-cn": "图标"
    },
    "imageFalse": {
        "en": "icon",
        "de": "Symbol",
        "ru": "икона",
        "pt": "ícone",
        "nl": "icoon",
        "fr": "icône",
        "it": "icona",
        "es": "icono",
        "pl": "Ikona",
        "zh-cn": "图标"
    },
    "imageTrue": {
        "en": "active icon",
        "de": "aktives Symbol",
        "ru": "активный значок",
        "pt": "ícone ativo",
        "nl": "actief pictogram",
        "fr": "icône active",
        "it": "icona attiva",
        "es": "icono activo",
        "pl": "aktywna ikona",
        "zh-cn": "活动图标"
    },
    "invertImageFalse": {
        "en": "invert icon color",
        "de": "Symbolfarbe umkehren",
        "ru": "инвертировать цвет значка",
        "pt": "inverter cor do ícone",
        "nl": "kleur van het pictogram omkeren",
        "fr": "inverser la couleur de l'icône",
        "it": "inverti il colore dell'icona",
        "es": "invertir el color del icono",
        "pl": "odwróć kolor ikony",
        "zh-cn": "反转图标颜色"
    },
    "invertImageTrue": {
        "en": "invert active icon color",
        "de": "Aktive Symbolfarbe invertieren",
        "ru": "инвертировать активный цвет значка",
        "pt": "inverter cor do ícone ativo",
        "nl": "actieve pictogramkleur omkeren",
        "fr": "inverser la couleur de l'icône active",
        "it": "inverti il colore dell'icona attiva",
        "es": "invertir el color del icono activo",
        "pl": "odwróć aktywny kolor ikony",
        "zh-cn": "反转活动图标颜色"
    },
    "iconHeight": {
        "en": "icon size",
        "de": "Symbolgröße",
        "ru": "размер значка",
        "pt": "tamanho do ícone",
        "nl": "pictogramgrootte",
        "fr": "taille de l'icône",
        "it": "dimensione dell'icona",
        "es": "tamaño de ícono",
        "pl": "rozmiar ikony",
        "zh-cn": "图标大小"
    },
    "group_color": {
        "en": "colors",
        "de": "Farben",
        "ru": "цвета",
        "pt": "cores",
        "nl": "kleuren",
        "fr": "couleurs",
        "it": "colori",
        "es": "colores",
        "pl": "zabarwienie",
        "zh-cn": "颜色"
    },
    "colorBgFalse": {
        "en": "background",
        "de": "Hintergrund",
        "ru": "фон",
        "pt": "fundo",
        "nl": "achtergrond",
        "fr": "Contexte",
        "it": "sfondo",
        "es": "antecedentes",
        "pl": "tło",
        "zh-cn": "背景"
    },
    "colorBgTrue": {
        "en": "active background",
        "de": "aktiver Hintergrund",
        "ru": "активный фон",
        "pt": "fundo ativo",
        "nl": "actieve achtergrond",
        "fr": "fond actif",
        "it": "sfondo attivo",
        "es": "fondo activo",
        "pl": "aktywne tło",
        "zh-cn": "活动背景"
    },
    "labelColorBgFalse": {
        "en": "label background",
        "de": "Hintergrund Beschriftung",
        "ru": "фон метки",
        "pt": "fundo da etiqueta",
        "nl": "label achtergrond",
        "fr": "étiquette fond",
        "it": "etichetta di sfondo",
        "es": "etiqueta de fondo",
        "pl": "tło etykiety",
        "zh-cn": "标签背景"
    },
    "labelColorBgTrue": {
        "en": "active label background",
        "de": "aktiver Hintergrund Beschriftung",
        "ru": "фон активной метки",
        "pt": "fundo do rótulo ativo",
        "nl": "actieve label achtergrond",
        "fr": "étiquette active",
        "it": "etichetta attiva sullo sfondo",
        "es": "fondo de etiqueta activa",
        "pl": "aktywne tło etykiety",
        "zh-cn": "活动标签背景"
    },
    "colorPress": {
        "en": "color pressed",
        "de": "Farbe gedrückt",
        "ru": "цвет нажал",
        "pt": "cor pressionada",
        "nl": "kleur ingedrukt",
        "fr": "couleur pressée",
        "it": "colore premuto",
        "es": "color presionado",
        "pl": "kolor wciśnięty",
        "zh-cn": "压色"
    },
    "colorProgress": {
        "en": "color progress",
        "de": "Farbe Fortschritt",
        "ru": "прогресс цвета",
        "pt": "progresso da cor",
        "nl": "kleur vooruitgang",
        "fr": "progression de la couleur",
        "it": "progresso del colore",
        "es": "progreso de color",
        "pl": "postęp kolorów",
        "zh-cn": "颜色进度"
    },
    "colorOneCondition": {
        "en": "condition for color 1 progress [>]",
        "de": "Bedingung für Farbe 1 Fortschritt [>]",
        "ru": "условие для прогресса цвета 1 [>]",
        "pt": "condição para o progresso da cor 1 [>]",
        "nl": "voorwaarde voor voortgang kleur 1 [>]",
        "fr": "condition pour la progression de la couleur 1 [>]",
        "it": "condizione per avanzamento colore 1 [>]",
        "es": "condición para el progreso del color 1 [>]",
        "pl": "warunek postępu koloru 1 [>]",
        "zh-cn": "颜色1进度的条件[>]"
    },
    "colorOne": {
        "en": "color 1 progress",
        "de": "Farbe 1 Fortschritt",
        "ru": "цвет 1 прогресс",
        "pt": "cor 1 progresso",
        "nl": "kleur 1 voortgang",
        "fr": "couleur 1 progrès",
        "it": "avanzamento colore 1",
        "es": "color 1 progreso",
        "pl": "postęp koloru 1",
        "zh-cn": "颜色1进度"
    },
    "colorTwoCondition": {
        "en": "condition for color 2 progress [>]",
        "de": "Bedingung für Farbe 2 Fortschritt [>]",
        "ru": "условие для прогресса цвета 2 [>]",
        "pt": "condição para o progresso da cor 2 [>]",
        "nl": "voorwaarde voor voortgang kleur 2 [>]",
        "fr": "condition pour la progression de la couleur 2 [>]",
        "it": "condizione per avanzamento colore 2 [>]",
        "es": "condición para el progreso del color 2 [>]",
        "pl": "warunek postępu koloru 2 [>]",
        "zh-cn": "颜色2进度的条件[>]"
    },
    "colorTwo": {
        "en": "color 2 progress",
        "de": "Farbe 2 Fortschritt",
        "ru": "цвет 2 прогресс",
        "pt": "progresso da cor 2",
        "nl": "kleur 2 voortgang",
        "fr": "couleur 2 progrès",
        "it": "avanzamento colore 2",
        "es": "progreso del color 2",
        "pl": "kolor 2 postępu",
        "zh-cn": "颜色2进展"
    },
    "colorSwitchTrue": {
        "en": "active switch color",
        "de": "aktive Schalterfarbe",
        "ru": "активный переключатель цвета",
        "pt": "cor do interruptor ativo",
        "nl": "actieve schakelaar kleur",
        "fr": "couleur active du commutateur",
        "it": "colore interruttore attivo",
        "es": "color de interruptor activo",
        "pl": "aktywny kolor przełącznika",
        "zh-cn": "活动开关颜色"
    },
    "colorSlider": {
        "en": "color Slider",
        "de": "Farbe Regler",
        "ru": "цветной слайдер",
        "pt": "controle deslizante de cor",
        "nl": "kleuren schuifregelaar",
        "fr": "couleur Slider",
        "it": "cursore a colori",
        "es": "control deslizante de color",
        "pl": "suwak koloru",
        "zh-cn": "彩色滑块"
    },
    "colorSliderBg": {
        "en": "background",
        "de": "Hintergrund",
        "ru": "фон",
        "pt": "fundo",
        "nl": "achtergrond",
        "fr": "Contexte",
        "it": "sfondo",
        "es": "antecedentes",
        "pl": "tło",
        "zh-cn": "背景"
    },
    "colorCheckBox": {
        "en": "active checkbox color",
        "de": "Farbe des aktiven Kontrollkästchens",
        "ru": "активный флажок цвет",
        "pt": "cor da caixa de seleção ativa",
        "nl": "actieve selectievakje kleur",
        "fr": "couleur de la case à cocher active",
        "it": "colore della casella di controllo attivo",
        "es": "color de casilla activa",
        "pl": "aktywny kolor pola wyboru",
        "zh-cn": "活动复选框颜色"
    },
    "group_drawerLabels": {
        "en": "label for navigation bar",
        "de": "Navigationsleiste: Beschriftungen",
        "ru": "ярлык для панели навигации",
        "pt": "etiqueta para barra de navegação",
        "nl": "label voor navigatiebalk",
        "fr": "étiquette pour la barre de navigation",
        "it": "etichetta per barra di navigazione",
        "es": "etiqueta para barra de navegación",
        "pl": "etykieta dla paska nawigacji",
        "zh-cn": "导航栏标签"
    },
    "group_drawerIcons": {
        "en": "icons for navigation bar",
        "de": "Navigationsleiste: Symbole",
        "ru": "иконки для панели навигации",
        "pt": "ícones para barra de navegação",
        "nl": "pictogrammen voor navigatiebalk",
        "fr": "icônes pour la barre de navigation",
        "it": "icone per la barra di navigazione",
        "es": "iconos para barra de navegación",
        "pl": "ikony paska nawigacji",
        "zh-cn": "导航栏图标"
    },
    "iconDrawer": {
        "en": "icon",
        "de": "Symbol",
        "ru": "икона",
        "pt": "ícone",
        "nl": "icoon",
        "fr": "icône",
        "it": "icona",
        "es": "icono",
        "pl": "Ikona",
        "zh-cn": "图标"
    }
};